package com.kaisernova.modelo.enums;

public enum NombreParametroConfiguracion {
	TITULO,
	EMAIL_SIN_EMAIL_REGISTRADO,	
	MAXIMO_REGISTROS_MOSTRAR_DEFECTO,
	AMBIENTE_PRODUCTIVO,
	MES,
	MAIL_SERVER,
	MAIL_PORT,
	MAIL_USER,
	MAIL_PASSWORD,
	MAIL_AUTH,
	MAIL_ADMIN,
	MAIL_SSL,
	MAIL_REMITENTE,
	MAIL_NOMBRE_REMITENTE,
	MAIL_SMTP_STARTTLS_ENABLE,
	
	MAIL_ASUNTO_GENERAL,
	MAIL_MENSAJE_NOTIFICACION_REGISTRO_PACIENTE,
	MAIL_MENSAJE_RECUPERACION_CLAVE,
	MAIL_MENSAJE_NOTIFICACION_CITA_PACIENTE,
	MAIL_MENSAJE_NOTIFICACION_CITA_ESPECIALISTA,
	ASUNTO_GENERAL,
	MENSAJE_GENERAL,
	ASUNTO_ERROR,
	MENSAJE_ERROR,	
	TELEFONO_CONTACTO,
	EMAIL_CONTACTO,
	URL_CAPTCHA_CLIENTE,
	URL_CAPTCHA_SERVER,
	ACTIVAR_CAPTCHA,
	CAPTCHA_SITE_KEY,
	CAPTCHA_SECRET_KEY,
	CAPTCHA_MIN_SCORE,
	WHATSAPP_URL_BASE,
	WHATSAPP_ACTIVAR,
	WHATSAPP_NUMERO_CONTACTO,
	WHATSAPP_MENSAJE_DEFECTO,
	
	// Google Calendar credentials JSON stored here (string containing credentials.json)
	GOOGLE_CALENDAR_CREDENTIALS_JSON,
	// Google Calendar application name
	GOOGLE_CALENDAR_APP_NAME,
	// Port used by LocalServerReceiver for OAuth flow
	GOOGLE_CALENDAR_PORT,
	
	// Schedule time window configuration (HH:mm)
	SCHEDULE_MIN_TIME,
	SCHEDULE_MAX_TIME,
	METODOS_PAGO_HABILITADOS,
	GOOGLE_CALENDAR_TOKEN_DIR,
	URL_VIDEO_PRESENTACION_GENERAL,
	TERMINOS_Y_CONDICIONES,
	;
	
}