package com.kaisernova.modelo.enums;

public enum NombreParametroConfiguracion {
	TITULO,
	EMAIL_SIN_EMAIL_REGISTRADO,	
	MAXIMO_REGISTROS_MOSTRAR_DEFECTO,
	AMBIENTE_PRODUCTIVO,
	
	MAIL_SERVER,
	MAIL_PORT,
	MAIL_USER,
	MAIL_PASSWORD,
	MAIL_AUTH,
	MAIL_ADMIN,
	MAIL_SSL,
	MAIL_REMITENTE,
	MAIL_NOMBRE_REMITENTE,
	MAIL_SMTP_STARTTLS_ENABLE,
	
	MAIL_ASUNTO_GENERAL,

	MAIL_MENSAJE_RECUPERACION_CLAVE,

	ASUNTO_GENERAL,
	MENSAJE_GENERAL,
	ASUNTO_ERROR,
	MENSAJE_ERROR,	
	TELEFONO_CONTACTO,
	EMAIL_CONTACTO,
	URL_CAPTCHA_CLIENTE,
	URL_CAPTCHA_SERVER,
	ACTIVAR_CAPTCHA,
	CAPTCHA_SITE_KEY,
	CAPTCHA_SECRET_KEY,
	CAPTCHA_MIN_SCORE,
	WHATSAPP_URL_BASE,
	WHATSAPP_ACTIVAR,
	WHATSAPP_NUMERO_CONTACTO,
	WHATSAPP_MENSAJE_DEFECTO,

	TERMINOS_Y_CONDICIONES,
	METODOS_PAGO_HABILITADOS,
	SEPARADOR_CODIGO_CATEGORIA_PRODUCTO;
	;
	
}